### ISSUE TITLE
Add option to choose between Roles and ClusterRoles (restrict cluster creation to tinkerbell namespace)

### ISSUE THREAD

**Issue by d-card** [tinkerbell/charts#120]
This is related to pull-request #117.

I agree that users should be able to create clusters outside of the tinkerbell namespace. However, I believe they should also have the option to control access to the entire cluster, as unrestricted access shouldn't be the default or only option.

Currently, Rufio's Helm chart creates a ClusterRole that [grants read access to all cluster secrets](https://github.com/tinkerbell/charts/blob/feae73e4d74b8a6203229dc207a1d110da4fe9cc/tinkerbell/rufio/templates/cluster-role.yaml#L8-L17). While this might be acceptable if the cluster is dedicated solely to running Tinkerbell, it poses a security risk in a production environment where other workloads may be running. Specifically, allowing Rufio to read secrets from all namespaces can be a significant security concern, which some users may find unacceptable.

## Expected Behaviour
Users should have the ability to choose whether the Tinkerbell stack has access to multiple namespaces, enabling the creation of Cluster API clusters in namespaces other than tinkerbell.

## Current Behaviour
By default, Rufio has access to all secrets across all namespaces, with no option to change/disable this.

## Possible Solution
Introduce an option that allows users to decide whether to grant Rufio access to all namespaces or restrict it to the tinkerbell namespace. If possible, also provide the ability for users to specify which namespaces the Tinkerbell stack should have access to (instead of the entire cluster).

**Comment by chrisdoherty4** [comment]
Would the ability to disable parts/all RBAC in some fashion so you can craft your own be acceptable?

**Comment by d-card** [comment]
That would already be better than the current behavior, yes.
