### ISSUE TITLE
Update Hegel version to v0.8.0

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/charts#14]
## Expected Behaviour

Hegel just release [v0.8.0](https://github.com/tinkerbell/hegel/releases). We should update the helm chart to use this version.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by chrisdoherty4** [comment]
0.8 has been added to the 1.2 chart but the `appVersion` wasn't bumped to v0.8. It will be addressed with https://github.com/tinkerbell/charts/issues/16
