### ISSUE TITLE
Facility code to be added in stack values.yaml

### ISSUE THREAD

**Issue by shan100github** [tinkerbell/charts#41]
## Expected Behaviour
While we deploy tink-stack by updating only the following values.yaml, it needs to create tink-stack with respective values, 
https://github.com/tinkerbell/charts/blob/main/tinkerbell/stack/values.yaml#L43
It looks like the current main branch https://github.com/tinkerbell/charts/blob/main/tinkerbell/boots/templates/deployment.yaml#L51 it's hardcoded. It will be good to allow custom values set by the user.

**Comment by chrisdoherty4** [comment]
Hi @shan100github, thanks for raising. What's your motivation for wanting to tweak this? 

FYI, we intend on deprecating and removing the facility configuration across Tinkerbell.

**Comment by shan100github** [comment]
I thought its a miss during a recent change, got it.
let me close it.
