### ISSUE TITLE
Detection bug

### ISSUE THREAD

**Issue by kfox1111** [tinkerbell/charts#56]
## Expected Behaviour
tink-stack pod should start

## Current Behaviour
Its failing here on minikube:
https://github.com/tinkerbell/charts/blob/main/tinkerbell/stack/templates/nginx.yaml#L33C28-L33C67

resolve.conf on minikube looks like:
```
bash-4.4# more /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

Which doesn't match the awk script very well.

## Possible Solution

Change the script to:
```
awk '/nameserver/ {print $2}' /etc/resolv.conf
```

## Your Environment

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

minikube

**Comment by jacobweinstock** [comment]
Hey @kfox1111, thanks for the report! I opened a PR to resolve this.
