### ISSUE TITLE
Publish to artifacthub.io

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/charts#6]
Helm charts in OCI registries (for example ghcr.io) can be used as the backing for helm charts in artifacthub.io. https://artifacthub.io/docs/topics/repositories/helm-charts/#oci-support

Might be easy to push the helm chart to ghcr.io and then have artifacthub pull it from there.

**Comment by jacobweinstock** [comment]
Charts are now being published here: https://github.com/tinkerbell/charts/pkgs/container/charts%2Fstack. Once we figure out login info for the Tinkerbell account to artifacthub.io we can make the chart available there.

**Comment by kfox1111** [comment]
Any update on this?

**Comment by jacobweinstock** [comment]
Hey @kfox1111 , apologies for the very delayed response. Unfortunately, we're not going to be able to get to this. Hopefully the ghcr.io chart will be able to handle your requirements. I'm going to close this issue, but please feel free to continue to add any comments for discussion. Thanks!
