### ISSUE TITLE
How to access tink cli after deploying the tinkerbell stack on k8s?

### ISSUE THREAD

**Issue by rishi97** [tinkerbell/charts#76]
I have install the tink stack helm on k8s. But I dont see any pod/deployment created for tink-cli. 
<img width="1314" alt="image" src="https://github.com/tinkerbell/charts/assets/16346559/3519817e-9414-4704-859b-fad669cf1172">

## Expected Behaviour
Maybe there should be a seperate pod created for access to tink-cli 
OR Do I need to install tink-cli some other way?

## Environment

* Ubuntu 18.04 + K3s

* Running tinkerbell stack on k8s; deployed via tink stack helm chart

**Comment by chrisdoherty4** [comment]
Hi @rishi97. `tink-cli` has been obsolete and removed from the code base for quite some time. You interact with your data via `kubectl`. E.g. `kubectl get hardware`.
